### ISSUE TITLE
想知道是否有 public/WebGLBuild build 前的代码

### ISSUE THREAD

**Issue by bakapiano** [LingFeng-bbben/Majdata-Online#2]
还是说是由 [MajdataView](https://github.com/LingFeng-bbben/MajdataView) 项目直接 build 成的 webGL app？

如果不是的话方便开源学习一下吗，感谢！

**Comment by LingFeng-bbben** [comment]
fork在这里
https://github.com/Wh1tyEnd/MajdataView_web
