### ISSUE TITLE
有意对部分网页样式和部分功能作修缮

### ISSUE THREAD

**Issue by drnarika** [LingFeng-bbben/Majdata-Online#4]
有意对部分网页样式和部分功能作修缮。
包括但不限于：

- 固定顶栏
- 不同的夜间模式或日间模式颜色主题
- 使用指南和提示
- 铺面自动暂停和小窗播放功能
- 更方便的下载进度条
- 部分减少流量支出的缓存和性能优化

如果允许我就发pr。感谢。

**Comment by LingFeng-bbben** [comment]
感谢！！！
有关最后一项，现在是在使用cf进行缓存

**Comment by drnarika** [comment]
> 感谢！！！ 有关最后一项，现在是在使用cf进行缓存

收到。另外simai网页播放器的工程有开源打算吗？我看貌似有一些bug。

**Comment by LingFeng-bbben** [comment]
> 收到。另外simai网页播放器的工程有开源打算吗？我看貌似有一些bug。

在这：https://github.com/Wh1tyEnd/MajdataView_web
